# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZegoPrebuiltVideoConferenceDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoPrebuiltVideoConferenceDemo
  pod  'ZegoUIKitPrebuiltVideoConference'
end

post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY'] = ''
           end
      end
    end
  end